@startuml
top to bottom direction

namespace common {
    enum eView {
      Game
      Settings
    }
}

namespace app {
  class Manager

  interface IView {
    + join() : void
    + signal change(eView)
    + exit() : void
    + render() : void
    + type() : eView
  }

  Manager ..> "*" IView
}

namespace gui {
  class Game
  class Settings

  interface IKeyEvent {
    + event() : SDL_KeyCode
  }

  interface ISettings {
    + join() : void
    + signal change(eView)
    + exit() : void
    + render() : void
  }

  Settings ..|> app.IView
  Game ..|> app.IView
  Game ..> IKeyEvent
  Settings ..> ISettings
}

namespace settings {
    class Settings
    class Player

    interface IKeyEvent {
      + event() : SDL_KeyCode
    }

    Settings ..|> gui.ISettings
    Player ..|> gui.ISettings
    Settings ..> IKeyEvent
    Player ..> IKeyEvent
}

namespace event {
    class KeyEvent

    KeyEvent ..|> gui.IKeyEvent
    KeyEvent ..|> settings.IKeyEvent
}

@enduml
